# Generated by Django 4.0.3 on 2022-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
