# Generated by Django 4.0.3 on 2022-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_lists_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lists',
            old_name='task',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lists',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='lists',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
